### ISSUE TITLE
Will you introduce AB stability?

### ISSUE THREAD

**Issue by alekoleg** [infobip/infobip-rtc-ios#1]
Currently, the SDK locked to Swift 5.1. Do you have plans to add AB stability to get rid of locks to specific Xcode?

**Comment by mmujic** [comment]
Hello @alekoleg 
thank you for contacting us.
For our next release we are planning to enable library evolution and support 5.x Swift versions.

Please stay tuned.

**Comment by rsbydv** [comment]
Can you please provide just a compiled framework with latest Xcode, For just the short term basis. Meanwhile, you can work on the ABI stability and we can also continue our development. As this has become a real hurdle for our timelines.

**Comment by mmujic** [comment]
Hi again,
we published new version **1.1.0** with 5.x Swift support both on Cocoapods and Carthage.
Can you please check it out and confirm if it works?

**Comment by rsbydv** [comment]
Yes, it's working.
Thanks!

**Comment by mmujic** [comment]
Great, thanks for confirmation.
Good luck with coding.
