### ISSUE TITLE
Using the SDK as a Swift Package doesn't work

### ISSUE THREAD

**Issue by bas-d** [infobip/infobip-rtc-ios#3]
The issue seems to be that there are leading whitespaces in the `Package.swift` file.

**Comment by ajsa-terko** [comment]
Hello! Thank you for reporting found issues. Swift Package support is currently in a testing phase on our side.

This specific issue has been resolved and will be available correctly with the first release supporting the use of the SDK as a Swift Package.

As for the other issues, we are investigating possible solutions, and will let you know asap.

**Comment by ajsa-terko** [comment]
Hello, sorry for the delay. 

Swift Package support has been enabled for some time now. Please retest it, and let us know if the issue persists.
