### ISSUE TITLE
Failing to build on latest Xcode version

### ISSUE THREAD

**Issue by bas-d** [infobip/infobip-rtc-ios#5]
When building with the latest version of Xcode (13.3.1), the SDK causes the build the fail with the following error (build target iOS):
> /<path>InfobipClient.swift:9:8: Failed to build module 'InfobipRTC'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 effective-4.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.6 effective-4.2 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)'). Please select a toolchain which matches the SDK.

Perhaps this might solve it: https://stackoverflow.com/a/70562356

**Comment by ajsa-terko** [comment]
Hello, sorry for the delay. 

Swift Package support has been enabled for some time now. Please retest it, and let us know if the issue persists.
