### ISSUE TITLE
Failing to build for iOS Simulator

### ISSUE THREAD

**Issue by bas-d** [infobip/infobip-rtc-ios#6]
When building for iOS Simulator on M1, the SDK causes the build to fail with the following error:
> /Users/user/Library/Developer/Xcode/DerivedData/Project-ccxhwdqnrwclsffmbzepvtntonan/SourcePackages/artifacts/infobip-rtc-ios/InfobipRTC.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/bas/Library/Developer/Xcode/DerivedData/Project-ccxhwdqnrwclsffmbzepvtntonan/SourcePackages/artifacts/infobip-rtc-ios/InfobipRTC.xcframework'.

The package has been added with SPM.

**Comment by ajsa-terko** [comment]
Hello, sorry for the delay. 

Swift Package support has been enabled officially for some time now. This issue should be resolved, hence, there shouldn't be a problem when building for iOS Simulator on M1. 

Regards
