### ISSUE TITLE
OC projects cannot be found the getInfobipRTCInstance() method

### ISSUE THREAD

**Issue by iosLiuPeng** [infobip/infobip-rtc-ios#7]
Hello,

I want to use the InfobipRTC library in an OC project. When I import it using pod, the getInfobipRTCInstance() method cannot be found in the InfobipRTC-Swift.h file. This may be due to the fact that this method is not marked as supporting OC.

Hope it can be

public func getInfobipRTCInstance() -> InfobipRTC.InfobipRTC

Change to

@objc
public func getInfobipRTCInstance() -> InfobipRTC.InfobipRTC

**Comment by adnanel** [comment]
Hello

getInfobipRTCInstance cannot be marked as `@objc` as it's not a class member. 

However, we can make a version of it inside a class for the sake of obj c compatibility, as the rest of the SDK is already compatible.

We are releasing 2.2.11 soon (later today, hopefully), with a new method

```
InfobipRTCFactory.getInfobipRTCInstance()
```

Please try using that instead. We will also add it to the docs to make sure it's mentioned.

**Comment by adnanel** [comment]
The version `2.2.12` is released containing the new method. It's undocumented right now but will be in the following few days, feel free to start using it in the meantime.

Please let me know if you encounter any new problems when trying to use the SDK, otherwise feel free to close the issue.

**Comment by iosLiuPeng** [comment]
I have started using it, thank you for your prompt processing.
