### ISSUE TITLE
The EnablePushNotificationResult class in oc cannot obtain its properties

### ISSUE THREAD

**Issue by iosLiuPeng** [infobip/infobip-rtc-ios#8]
Problem: After bridging EnablePushNotificationResult to oc, the properties in it cannot be seen.

suggestion:

1. I hope to add a method to return the bool value corresponding to 'status'.

2. I hope that
final public let message: String
Mark as
@objc final public let message: String

Another good thing is that I have successfully connected to 'InfobipRTC' and implemented the call function, but I have not yet found how to enableAudio and disableAudio. I hope I can do it in CallKit
- Provider: didActivateAudioSession: and - provider: didDeactivateAudioSession: Delegate methods to control Audio

**Comment by adnanel** [comment]
Hi!
Terribly sorry for the slow response, version 2.3.1 is released and contains a fix for this.

Let us know if you encounter any other problems.
